### PR TITLE
Fix bug in finder's query form serialization with special characters

### PR DESCRIPTION
**Pull request by pgrunewald**
For further discussion see:

* http://www.w3schools.com/jsref/jsref_unescape.asp
* https://stackoverflow.com/questions/619323/decodeuricomponent-vs-unescape-what-is-wrong-with-unescape

I would be delighted to see this merged. :)

regards

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @pgrunewald 

could you please tell me how to repoduce the problem you encountered so I can test?

Thank you!

Gauthier

**Comment by pgrunewald** [comment]
Sure, but I can only speak for our setup (we use collective.ckeditor which utilizes plonefinder). Open your WYSIWYG editor and try to create a hyperlink to a local object with the finder view.

Using the search form and entering letters such äÄüÜß causes a malformed string, which grows even worse by repeat sending the very same form. For example the word "ähnlich" will be become "ÃÂÃÂ¤hnlich" and so on.

Which won't happen with my patch.

**Comment by gbastien** [comment]
We also use it thru collective.ckeditor, just tested (we actually have the exact same problem as we use special characters like "problème" or "aînés"), it seems like our users do not use the search widget ;-)

**Comment by gbastien** [comment]
@pgrunewald 

I released version 1.1.4 : https://pypi.python.org/pypi/collective.plonefinder

Gauthier

**Comment by pgrunewald** [comment]
Hello @gbastien 

great! Thanks for the fast response. :)

regards

**Pull request merged**
